# Generated by Django 2.2 on 2020-09-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_artikel_gambar'),
    ]

    operations = [
        migrations.CreateModel(
            name='surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50)),
                ('nama', models.TextField(max_length=20)),
            ],
        ),
    ]
