# Generated by Django 2.2 on 2020-09-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_dua'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayat', models.CharField(max_length=10)),
                ('isi', models.CharField(max_length=1000)),
                ('cluster', models.CharField(max_length=10)),
            ],
        ),
    ]
