# Generated by Django 2.2 on 2020-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tiga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satu',
            name='isi',
            field=models.TextField(max_length=1000),
        ),
    ]
