# Generated by Django 2.2 on 2020-10-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_cluster2'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no3', models.CharField(max_length=10)),
                ('surat3', models.TextField(max_length=1000)),
                ('ayat3', models.CharField(max_length=20)),
                ('terjemah3', models.TextField(max_length=1000)),
            ],
        ),
    ]
