# Generated by Django 2.2 on 2020-10-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_cluster3'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no4', models.CharField(max_length=10)),
                ('surat4', models.TextField(max_length=1000)),
                ('ayat4', models.CharField(max_length=20)),
                ('terjemah4', models.TextField(max_length=1000)),
            ],
        ),
    ]
