# Generated by Django 2.2 on 2020-10-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_cluster4'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no5', models.CharField(max_length=10)),
                ('surat5', models.TextField(max_length=1000)),
                ('ayat5', models.CharField(max_length=20)),
                ('terjemah5', models.TextField(max_length=1000)),
            ],
        ),
    ]
