# Generated by Django 2.2 on 2020-10-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_cluster5'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no6', models.CharField(max_length=10)),
                ('surat6', models.TextField(max_length=1000)),
                ('ayat6', models.CharField(max_length=20)),
                ('terjemah6', models.TextField(max_length=1000)),
            ],
        ),
    ]
