# Generated by Django 2.2 on 2020-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_cluster6'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no7', models.CharField(max_length=10)),
                ('surat7', models.TextField(max_length=1000)),
                ('ayat7', models.CharField(max_length=20)),
                ('terjemah7', models.TextField(max_length=1000)),
            ],
        ),
    ]
